/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main */

#ifndef _Included_main
#define _Included_main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main
 * Method:    javaCall
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_javaCall
  (JNIEnv *, jclass);

/*
 * Class:     main
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
