/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main */

#ifndef _Included_main
#define _Included_main
#ifdef __cplusplus
extern "C" {
#endif
#undef main_FOCUS_TRAVERSABLE_UNKNOWN
#define main_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef main_FOCUS_TRAVERSABLE_DEFAULT
#define main_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef main_FOCUS_TRAVERSABLE_SET
#define main_FOCUS_TRAVERSABLE_SET 2L
#undef main_TOP_ALIGNMENT
#define main_TOP_ALIGNMENT 0.0f
#undef main_CENTER_ALIGNMENT
#define main_CENTER_ALIGNMENT 0.5f
#undef main_BOTTOM_ALIGNMENT
#define main_BOTTOM_ALIGNMENT 1.0f
#undef main_LEFT_ALIGNMENT
#define main_LEFT_ALIGNMENT 0.0f
#undef main_RIGHT_ALIGNMENT
#define main_RIGHT_ALIGNMENT 1.0f
#undef main_serialVersionUID
#define main_serialVersionUID -7644114512714619750LL
#undef main_serialVersionUID
#define main_serialVersionUID 4613797578919906343LL
#undef main_INCLUDE_SELF
#define main_INCLUDE_SELF 1L
#undef main_SEARCH_HEAVYWEIGHTS
#define main_SEARCH_HEAVYWEIGHTS 1L
#undef main_OPENED
#define main_OPENED 1L
#undef main_serialVersionUID
#define main_serialVersionUID 4497834738069338734LL
#undef main_DEFAULT_CURSOR
#define main_DEFAULT_CURSOR 0L
#undef main_CROSSHAIR_CURSOR
#define main_CROSSHAIR_CURSOR 1L
#undef main_TEXT_CURSOR
#define main_TEXT_CURSOR 2L
#undef main_WAIT_CURSOR
#define main_WAIT_CURSOR 3L
#undef main_SW_RESIZE_CURSOR
#define main_SW_RESIZE_CURSOR 4L
#undef main_SE_RESIZE_CURSOR
#define main_SE_RESIZE_CURSOR 5L
#undef main_NW_RESIZE_CURSOR
#define main_NW_RESIZE_CURSOR 6L
#undef main_NE_RESIZE_CURSOR
#define main_NE_RESIZE_CURSOR 7L
#undef main_N_RESIZE_CURSOR
#define main_N_RESIZE_CURSOR 8L
#undef main_S_RESIZE_CURSOR
#define main_S_RESIZE_CURSOR 9L
#undef main_W_RESIZE_CURSOR
#define main_W_RESIZE_CURSOR 10L
#undef main_E_RESIZE_CURSOR
#define main_E_RESIZE_CURSOR 11L
#undef main_HAND_CURSOR
#define main_HAND_CURSOR 12L
#undef main_MOVE_CURSOR
#define main_MOVE_CURSOR 13L
#undef main_NORMAL
#define main_NORMAL 0L
#undef main_ICONIFIED
#define main_ICONIFIED 1L
#undef main_MAXIMIZED_HORIZ
#define main_MAXIMIZED_HORIZ 2L
#undef main_MAXIMIZED_VERT
#define main_MAXIMIZED_VERT 4L
#undef main_MAXIMIZED_BOTH
#define main_MAXIMIZED_BOTH 6L
#undef main_serialVersionUID
#define main_serialVersionUID 2673458971256075116LL
/*
 * Class:     main
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_hello
  (JNIEnv *, jclass);

/*
 * Class:     main
 * Method:    javaCall
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_javaCall
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
